fetching categories from api
mJurczuk91/musicshop pull request #2
Opened 2023-12-14 15:21 UTC by mJurczuk91

2023-12-19 14:47 UTC, mkokosinski requested changes

2023-12-19 14:47 UTC, mkokosinski commented on app/(lib)/data.ts
> +    if(!process.env.CATEGORIES) throw new Error('Categories env resource not found');
przenieś endpointy do zmiennych

2023-12-19 14:47 UTC, mkokosinski commented on app/(lib)/data.ts
> +export async function fetchCategories() : Promise<Category[]>{
wyciągnij obsługę do osobnej funkcji np get, api.get etc.

2023-12-19 14:47 UTC, mkokosinski commented on db.js
> +// json-server --port=3001 --watch db.js
usuń komentarz

2023-12-20 22:41 UTC, mJurczuk91 commented on app/(lib)/data.ts
> +    if(!process.env.CATEGORIES) throw new Error('Categories env resource not found');
https://github.com/mJurczuk91/musicshop/pull/2/commits/45ab79a500d43b59084ece53a5e5cab96273682b

2023-12-20 22:41 UTC, mJurczuk91 commented on app/(lib)/data.ts
> +export async function fetchCategories() : Promise<Category[]>{
https://github.com/mJurczuk91/musicshop/pull/2/commits/45ab79a500d43b59084ece53a5e5cab96273682b

2023-12-20 22:42 UTC, mJurczuk91 commented on db.js
> +// json-server --port=3001 --watch db.js
https://github.com/mJurczuk91/musicshop/pull/2/commits/070c83c5f0c0dacadb826d5ac0c0b9ff4344c609

2023-12-23 19:05 UTC, merged