responsive product grid done
mJurczuk91/musicshop pull request #3
Opened 2023-12-15 11:54 UTC by mJurczuk91

2023-12-19 14:54 UTC, mkokosinski requested changes

2023-12-19 14:54 UTC, mkokosinski commented on app/ui/productMiniature.tsx
> +    const description_short = description.length > 30 ? description.slice(0, 29) : description;
ternary jest niepotrzebny

2023-12-19 14:54 UTC, mkokosinski commented on app/ui/responsiveProductGrid.tsx
> +export default function ResponsiveProductGrid({ sectionTitle, products }: { sectionTitle: string, products: Product[] }) {
stwórz typ nad komponentem

2023-12-19 14:54 UTC, mkokosinski commented on app/ui/responsiveProductGrid.tsx
> +        <h2 className=" text-2xl uppercase font-bold text-center">{sectionTitle}</h2>
sprawdź czy na stronie masz już h1

2023-12-20 22:52 UTC, mJurczuk91 commented on app/ui/responsiveProductGrid.tsx
> +export default function ResponsiveProductGrid({ sectionTitle, products }: { sectionTitle: string, products: Product[] }) {
https://github.com/mJurczuk91/musicshop/pull/3/commits/14b33189e3eb00b118e1caee8db93a85cd4a4cc0

2023-12-20 22:52 UTC, mJurczuk91 commented on app/ui/productMiniature.tsx
> +    const description_short = description.length > 30 ? description.slice(0, 29) : description;
https://github.com/mJurczuk91/musicshop/pull/3/commits/ff245a5e96f6ae268c8a68c9a6db16f15935df03

2023-12-20 22:52 UTC, mJurczuk91 commented on app/ui/responsiveProductGrid.tsx
> +        <h2 className=" text-2xl uppercase font-bold text-center">{sectionTitle}</h2>
jest, jako nazwa sklepu

2023-12-23 19:07 UTC, merged